import { writeFile } from 'node:fs/promises';
import { brand as b, copy as c, faq, comparison, media } from './content.mjs';
import { mark, buildIdentity } from './identity.mjs';
const e = value => String(value).replaceAll('BetterTile',b.name).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const iconPaths = {
  down:'M12 4v16m-6-6 6 6 6-6', up:'M12 20V4m-6 6 6-6 6 6',
  external:'M7 17 17 7M7 7h10v10', play:'m8 5 11 7-11 7Z', pause:'M8 5v14M16 5v14',
  replay:'M4 10a8 8 0 1 1 1 8M4 4v6h6', menu:'M5 8h14M5 16h14', plus:'M5 12h14M12 5v14', close:'m6 6 12 12M6 18 18 6',
  resize:'M3 12h18M7 8l-4 4 4 4m10-8 4 4-4 4',
  keyboard:'M3 5h18v14H3ZM7 9h.01M11 9h.01M15 9h.01M18 9h.01M7 13h.01M11 13h.01M15 13h.01M7 16h10',
  undo:'M8 5 3 10l5 5M3 10h11a6 6 0 0 1 0 12',
};
const icon = (name,cls='') => `<svg class="ui-icon ${cls}" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[name]}"/></svg>`;
const link = (url, text, cls='') => `<a href="${url}"${cls?` class="${cls}"`:''}>${text.replaceAll('↗',icon('external'))}</a>`;
const download = (small=false) => link(b.links.download,`Download beta ${icon('down')}`,`button primary${small?' compact':''}`);
const logo = () => `<img class="logo-dark" src="${b.assets.icon}" width="40" height="40" alt=""><img class="logo-light" src="${b.assets.iconLight}" width="40" height="40" alt=""><span>${e(b.name)}</span>`;
const title = (item, id) => `<h2 id="${id}">${item.title.map(e).join('<br><span>')}</span></h2><p class="body-copy">${e(item.body)}</p>`;
const mediaFigure = key => {
  const item=media[key];
  return `<figure class="feature-media media-${key}" data-feature-media="${key}" style="--media-ratio:${item.width}/${item.height}">
    <video id="video-${key}" autoplay loop muted playsinline preload="none" width="${item.width}" height="${item.height}" poster="${item.poster}" data-video-src="${item.src}" aria-label="${e(item.alt)}"></video>
    <div class="media-footer"><figcaption>${e(item.caption)}</figcaption><button class="video-toggle" data-paused="true" aria-controls="video-${key}" aria-label="Play ${e(item.caption)} video" title="Play video" hidden>${icon('pause','control-pause')}${icon('play','control-play')}</button></div>
    <p class="video-error" role="status" hidden>Video could not load. Try playing it again.</p>
    <noscript><a class="text-link" href="${item.src}">Open ${e(item.caption)} video</a></noscript>
  </figure>`;
};
const appearanceToggle = `<button class="theme-toggle" aria-label="Switch to light mode" title="Switch to light mode"><svg class="theme-sun" viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg><svg class="theme-moon" viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M20.5 13.1A8.8 8.8 0 0 1 10.9 3.5a8.8 8.8 0 1 0 9.6 9.6Z"/></svg></button>`;
const restoreAppearance = `<script>try{const p=JSON.parse(localStorage.getItem('bettertile-appearance')||'{}');document.documentElement.dataset.theme=p.theme==='light'?'light':'dark';}catch{}</script>`;

const head = (isBrand=false) => `<!doctype html><html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="dark light"><meta name="theme-color" content="#07090d"><title>${e(b.name)} — ${isBrand?'Brand studio':e(b.tagline)}</title><meta name="description" content="${e(b.description)}"><meta property="og:type" content="website"><meta property="og:title" content="${e(b.name)} — ${e(b.tagline)}"><meta property="og:description" content="${e(b.description)}"><meta property="og:image" content="${b.site}assets/identity/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${e(b.name)}: ${e(b.tagline)}"><meta name="twitter:card" content="summary_large_image">${isBrand?'<meta name="robots" content="noindex">':`<link rel="canonical" href="${b.site}">`}<link rel="icon" type="image/png" href="assets/identity/app-icon-native-dark-32.png"><link rel="apple-touch-icon" href="${b.assets.iconLightLarge}">${isBrand?'':restoreAppearance}<link rel="stylesheet" href="${isBrand?'brand-base.css':'redesign.css'}">${isBrand?'<link rel="stylesheet" href="brand.css">':'<script type="module" src="redesign.js"></script>'}</head>`;

const home = `${head()}<body class="product-page"><a class="skip-link" href="#main">Skip to content</a>

<header class="site-header wrap"><a class="wordmark" href="./" aria-label="${e(b.name)} home">${logo()}</a><nav class="desktop-nav" aria-label="Main navigation"><a href="#features">Features</a><a href="#start">How it works</a>${link(b.links.github,'GitHub')}</nav><div class="header-actions">${download(true)}${appearanceToggle}<button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="Open navigation">${icon('menu')}</button></div><nav id="mobile-menu" class="mobile-nav" aria-label="Mobile navigation" hidden><a href="#features">Features</a><a href="#start">How it works</a>${link(b.links.github,'GitHub')}</nav></header>
<main id="main">
<section class="hero wrap" aria-labelledby="hero-title">
  <div class="hero-grid"><h1 id="hero-title">${e(c.hero.title[0])}<br>${e(c.hero.title[1])}</h1><div class="hero-copy"><p>${e(c.hero.body)}</p><div class="actions">${download()}<a class="text-button" href="#overview">${icon('play')} Watch demo</a></div><p class="hero-meta">${e(c.hero.note)} · ${e(b.requirement)}</p></div></div>
  <div id="overview" class="overview">${mediaFigure('overview')}</div>
  <nav id="features" class="feature-index" aria-label="Explore features"><a href="#linked">Linked resizing</a><a href="#bento">Bento</a><a href="#snapping">Snapping</a><a href="#tabbed">Tabbed</a><a href="#wheel">Layout Wheel</a><a href="#keyboard">Shortcuts</a></nav>
</section>
<section class="media-section media-row bento-section wrap section" id="bento" aria-labelledby="bento-title"><div class="media-copy"><h2 id="bento-title">${c.bento.title.map(e).join('<br>')}</h2><p>${e(c.bento.body)}</p><a href="#start" class="text-link">Get started ${icon('external')}</a></div>${mediaFigure('bento')}</section>
<section class="media-section media-row media-flip wrap section" id="linked" aria-labelledby="linked-title"><div class="media-copy"><h2 id="linked-title">Resize together.<br>Stay aligned.</h2><p>${e(c.linked.body)}</p><p class="fine">${e(c.linked.detail)}</p></div>${mediaFigure('linked')}</section>
<section class="media-section media-row wrap section" id="snapping" aria-labelledby="snapping-title"><div class="media-copy"><h2 id="snapping-title">See the fit.<br>Then let go.</h2><p>Drag a title bar toward an edge or corner. Preview the placement, then release to snap into place.</p></div>${mediaFigure('snapping')}</section>
<div class="feature-pair wrap section">
  <section class="feature-card" id="tabbed" aria-labelledby="tabbed-title"><div class="media-copy"><h2 id="tabbed-title">More within reach.<br>Less on the surface.</h2><p>Tabbed groups windows in resizable panes. Select a tab to bring its window forward.</p><p class="fine">Turn off Stage Manager for Tabbed. Pane assignments last for the current app session. ${link(b.links.limitations,'Beta details ↗')}</p></div>${mediaFigure('tabbed')}</section>
  <section class="feature-card" id="wheel" aria-labelledby="wheel-title"><div class="media-copy"><h2 id="wheel-title">Your next move.<br>Within reach.</h2><p>Open the Layout Wheel: hold <kbd>⌃</kbd> <kbd>⌥</kbd> <kbd>⇧</kbd>, choose a sector, and release. Configure the actions in Settings.</p><p class="fine">Escape or the center cancels. Optional middle click reserves that button system-wide while enabled.</p></div>${mediaFigure('wheel')}</section>
</div>
<section class="media-section media-row media-flip wrap section" id="keyboard" aria-labelledby="keyboard-title"><div class="media-copy"><h2 id="keyboard-title">Keep your hands<br>on the keys.</h2><p>Place windows with global shortcuts. Undo a placement when you want to try another arrangement.</p><p class="fine">Configure your shortcuts in Settings, with duplicate checks.</p></div>${mediaFigure('keyboard')}</section>
<section class="ownership wrap section" aria-labelledby="ownership-title"><div><h2 id="ownership-title">Your windows.<br><span>Your workspace.</span></h2><p class="body-copy">${e(c.ownership.body)}</p>${link(b.links.github,`Explore the source ${icon('external')}`,'text-link')}</div><div class="ownership-points"><article><div><h3>Free, with no second tier.</h3><p>The whole app. Open source under GPL v3 or later.</p></div></article><article><div><h3>Window data stays on your Mac.</h3><p>Update checks contact GitHub and can be turned off. No behavioral tracking. ${link(b.links.security,'Read the network disclosure ↗')}</p></div></article><article><div><h3>One permission, explained.</h3><p>Accessibility lets ${e(b.name)} move and resize your windows.</p></div></article></div></section>

<section class="comparison-section wrap section" aria-labelledby="comparison-title"><div class="section-heading"><div><h2 id="comparison-title">Different ways<br><span>to make space.</span></h2></div><p>There are good tools in this category. Choose the interaction that suits your work.</p></div><div class="comparison-table" role="region" aria-label="Window manager comparison"><table><caption>Workflow comparison · sources checked ${e(b.checked)}</caption><thead><tr><th scope="col">Product</th><th scope="col">A good fit for</th><th scope="col">Coordinated windows</th><th scope="col">Ownership</th></tr></thead><tbody>${comparison.map((row,i)=>`<tr${i===0?' class="our-row"':''}><th scope="row">${i===0?`<img class="comparison-icon" src="${b.assets.icon}" width="32" height="32" alt="">`:''}${e(row.name)}</th><td data-label="A good fit for">${e(row.fit)}</td><td data-label="Coordinated windows">${e(row.resize)}<div class="table-sources">${link(row.source,'Source ↗')} ${link(row.extra,e(row.extraLabel)+' ↗')}</div></td><td data-label="Ownership">${e(row.ownership)}</td></tr>`).join('')}</tbody></table></div><p class="fine comparison-note">“Not verified” is not a claim of no support. Prices are the values displayed on the check date; Moom’s page did not state a currency code. ${link('https://rectangleapp.com/','Free Rectangle')} and ${link('https://github.com/MrKai77/Loop','Loop')} also offer free placement tools. ${link('research/category.md','Full research and sources ↗')}</p></section>

<section id="start" class="getting-started wrap section" aria-labelledby="start-title"><div class="section-heading"><div><h2 id="start-title">Make the first move.</h2></div><p>${e(b.requirement)}<br>Public beta · Free forever</p></div><ol class="install-steps"><li><span>01</span><h3>Download the beta.</h3><p>Get the disk image from the official GitHub release. Open it and drag ${e(b.name)} into Applications.</p>${link(b.links.download,'Get the latest release ↗','text-link')}</li><li><span>02</span><h3>Allow the first launch.</h3><p>The beta is self-signed, without Apple Developer ID or notarization. After the first launch attempt, confirm the source, then choose <b>Open Anyway</b> in System Settings → Privacy &amp; Security.</p></li><li><span>03</span><h3>Give your windows room.</h3><p>Follow the app’s explanation to grant Accessibility permission. Choose your layout and enable the controls you want.</p>${link(b.links.install,'Full installation guide ↗','text-link')}</li></ol></section>

<section class="faq-section wrap section" aria-labelledby="faq-title"><div><h2 id="faq-title">A few<br><span>good questions.</span></h2></div><div class="faq-list">${faq.map(([q,a],i)=>`<details><summary>${e(q)}<span class="faq-indicator" aria-hidden="true">${icon('plus')}</span></summary><p>${e(a)}${i===5?' '+link(b.links.limitations,'Full beta limitations ↗'):i===3?' '+link(b.links.security,'Security and privacy ↗'):''}</p></details>`).join('')}</div></section>

<section class="closing wrap section" aria-labelledby="closing-title"><div class="closing-mark"><img class="logo-dark" src="${b.assets.iconLarge}" width="100" height="100" alt=""><img class="logo-light" src="${b.assets.iconLightLarge}" width="100" height="100" alt=""></div><h2 id="closing-title">${e(b.headline[0])}<br><span>${e(b.headline[1])}</span></h2>${download()}<p class="fine">${e(b.requirement)} · Free forever · Open source</p><p class="fine">Self-signed beta. ${link(b.links.install,'First-install instructions ↗')}</p></section>
</main><footer class="site-footer wrap"><a class="wordmark" href="./">${logo()}</a><nav aria-label="Footer navigation">${link(b.links.github,'Source')}${link(b.links.releases,'Releases')}${link(b.links.docs,'Docs')}${link(b.links.security,'Privacy & security')}${link(b.links.license,'License')}${link('ACKNOWLEDGEMENTS.md','Acknowledgements')}</nav><p>Made for the work in front of you.</p></footer>
</body></html>`;

const tile=(name,number,cls,concept,headline,body,palette)=>`<article class="style-tile ${cls}"><div class="tile-label"><span>0${number} / ${name}</span><span>${number===1?'Earlier exploration':'Exploration'}</span></div><div class="tile-logo">${mark(concept)}<span>${e(b.name)}</span></div><div class="tile-hero"><h3>${headline}</h3><div class="tile-panes"><i></i><b></b><i></i></div></div><p>${body}</p><div class="tile-palette">${palette.map(([color,label])=>`<span style="--swatch:${color}"><i></i>${label}</span>`).join('')}</div><p class="tile-type">${number===1?'Inter · Precise / spacious / connected':number===2?'Instrument Serif + Inter · Editorial / airy / thoughtful':'System sans + mono labels · Compact / focused / direct'}</p></article>`;

const brandPage=`${head(true)}<body class="brand-page"><a class="skip-link" href="#main">Skip to content</a><header class="site-header wrap"><a class="wordmark" href="./">${logo()}</a><a class="button secondary compact" href="./">View website ↗</a></header><main id="main" class="wrap"><section class="brand-intro section"><p class="eyebrow">Brand studio / Working proposal / ${e(b.checked)}</p><h1>A shared edge.<br><span>A clearer identity.</span></h1><p class="body-copy">A connected identity for ${e(b.name)}, built around the moment two windows move together. Proposed assets only; the native app has not been changed.</p><div class="actions">${link('BRAND-GUIDE.md','Read the brand guide ↗','button secondary')}${link('research/summary.md','Research & positioning ↗','text-link')}</div></section>
<section class="brand-section icon-colorways" id="icon-colorways"><h2>One icon. Two colorways.</h2><p class="body-copy">Current Ice Blue and Dark icons, exported from the native Icon Composer documents.</p><div class="colorway-pair">${[['light','Ice Blue','Ice-blue body, cobalt panes, mint and teal.'],['dark','Dark','Dark body, cobalt panes, mint and teal.']].map(([id,label,description])=>`<article><img src="assets/identity/app-icon-native-${id}-512.png" width="320" height="320" alt="${label} app icon"><h3>${label}</h3><p>${description}</p><a class="text-link" href="assets/identity/app-icon-native-${id}-1024.png" download>Download master PNG ↗</a><a class="text-link" href="assets/identity/app-icon-native-${id}-1024.png" download>1024 px PNG ↗</a><div class="icon-size-strip">${[16,24,32,64,128].map(size=>`<figure><img src="assets/identity/app-icon-native-${id}-${size<=32?32:size}.png" width="${size}" height="${size}" alt=""><figcaption>${size} px</figcaption></figure>`).join('')}</div></article>`).join('')}</div><p class="fine">These transparent PNGs come from the current native icon exports. Their editable source is in Resources/AppIconIce.icon and Resources/AppIconDark.icon. Earlier vector explorations remain below for reference.</p></section><section class="brand-section" aria-labelledby="directions"><p class="eyebrow">01 / Three directions</p><h2 id="directions">Different expressions.<br><span>One useful idea.</span></h2><div class="style-tiles">${tile('Shared Edge',1,'direction-edge','rail','Make room<br><span>for your work.</span>','An earlier direction with pitch black fading into cobalt, open frames, and one active teal boundary. The interface explains the identity; the identity explains the interface.',[['#000000','Black'],['#315cf4','Cobalt'],['#63dec0','Teal']])}${tile('Open Space',2,'direction-open','frame','A place<br><em>to think.</em>','A cool, bright editorial direction with an adaptable frame. Spacious and approachable, with less connection to the current dark app icon.',[['#f1f4f7','Paper'],['#1b2434','Ink'],['#405be8','Ultramarine']])}${tile('Quiet Instrument',3,'direction-instrument','type','WINDOWS.<br>IN CONCERT.','A compact typographic mark and monochrome utility language. Precise, but less welcoming and less direct about linked resizing.',[['#0b0d10','Black'],['#e9eef5','Silver'],['#a7b3c2','Slate']])}</div></section>
<section class="brand-section"><div class="section-heading"><div><p class="eyebrow">02 / Symbol explorations</p><h2>Draw the relationship.</h2></div><p>Three original constructions. Earlier vector studies. The Midnight website now uses the supplied glass icon, shown above.</p></div><div class="logo-concepts"><article>${mark('rail')}<h3>A / Shared rail</h3><p>Two open brackets and a taller common edge. Recognizable in one color. The gap stays useful at small sizes.</p></article><article>${mark('frame')}<h3>B / Adaptable frame</h3><p>An offset frame makes room for another shape. More architectural, but less immediately about linked movement.</p></article><article>${mark('type')}<h3>C / Joined initials</h3><p>A drawn B and T share a baseline. Name-dependent, with less visual separation at menu-bar sizes.</p></article></div></section>
<section class="brand-section"><p class="eyebrow">03 / Developed identity</p><h2>Separate windows.<br><span>Common ground.</span></h2><div class="identity-lockup">${mark()}<span>${e(b.name)}</span></div><div class="identity-examples"><div class="identity-light"><img src="assets/identity/symbol-mono.svg" width="110" height="110" alt="Monochrome Shared Edge symbol"><span>Monochrome</span></div><div><img src="assets/identity/symbol-white.svg" width="110" height="110" alt="White Shared Edge symbol"><span>Reversed</span></div><div class="icon-pair"><img src="assets/app-icon.png" width="108" height="108" alt="Current BetterTile app icon"><img src="${b.assets.icon}" width="128" height="128" alt="Current native Dark app icon"><span>Classic → native Dark icon</span></div></div><div class="small-size-test">${[16,24,32,64,128].map(size=>`<figure><img src="assets/identity/symbol-${size}.svg" width="${size}" height="${size}" alt="Shared Edge at ${size} pixels"><figcaption>${size} px</figcaption></figure>`).join('')}</div><p class="fine">The 16 px version uses a separate pixel-aligned drawing. Core silhouette tested without blur, gradients, or animation. Menu bar uses one opaque color.</p><div class="context-grid"><div class="menu-context"><span>Finder &nbsp; File &nbsp; Edit</span><img src="assets/identity/menu-bar.svg" width="16" height="16" alt="Proposed monochrome menu bar icon"><span>9:41</span></div><div class="download-context"><img src="${b.assets.icon}" width="64" height="64" alt="Native Dark app icon"><div><b>${e(b.name)}</b><p>A little more room.</p></div>${download(true)}</div></div><img class="social-example" src="assets/identity/social-preview.svg" width="1200" height="630" alt="Social preview showing BetterTile's headline, symbol, and a shared window boundary" loading="lazy"><div class="asset-links">${['symbol.svg','symbol-mono.svg','symbol-reversed.svg','wordmark.svg','lockup.svg','lockup-reversed.svg','favicon.svg','app-icon-concept.svg','menu-bar.svg','social-preview.svg'].map(file=>link('assets/identity/'+file,file)).join('')}</div><p class="fine">SVGs are editable. Wordmark files use Inter; the font and OFL license are bundled. The complete set also includes white and small-size symbols.</p></section>
<section class="brand-section" id="naming"><p class="eyebrow">04 / Naming recommendation</p><h2>Keep ${e(b.name)}.<br><span>Give it a signature.</span></h2><p class="body-copy">The name is clear, easy to say, and already belongs to this product’s public history. The “Better” prefix is less distinctive beside BetterTouchTool and BetterSnapTool. A recognizable shared-boundary identity is a stronger immediate change than a rename with unresolved conflicts.</p><div class="name-previews"><article><span class="eyebrow">Space & focus</span><h3>Panehaven</h3><p><b>PAYN-hay-vən</b><br>A calm home for windows. Clear connection, but long and close to an existing creative title. The .com is registered.</p><div class="name-logo">${mark('frame')}<span>Panehaven</span></div></article><article><span class="eyebrow">Connected movement</span><h3>Tandrow</h3><p><b>TAN-droh</b><br>Tandem + row. Short and active. Similar to the existing Tandro app and its pending US software trademark; not recommended.</p><div class="name-logo">${mark()}<span>Tandrow</span></div></article><article><span class="eyebrow">Invented / arrangement</span><h3>Tessune</h3><p><b>tess-OON</b><br>Tessellation + attune. Distinctive sound, less obvious meaning. Nearby Tessuno software and a registered .com remain concerns.</p><div class="name-logo">${mark('rail')}<span>Tessune</span></div></article></div><p class="fine">Exploratory previews, not an official rename. Limited searches are not trademark clearance or proof of domain availability. ${link('research/naming.md','Read all 12 candidates, evidence, and limitations ↗')}</p></section>
<section class="brand-section"><p class="eyebrow">05 / Brand foundation</p><div class="foundation-grid"><article><h3>Promise</h3><p>Keep your windows working together, so your attention can stay on the work.</p></article><article><h3>Personality</h3><p>Precise. Calm. Approachable.</p></article><article><h3>Voice</h3><p>Say what happens. Explain the next move. Prefer concrete verbs and honest beta details to performance claims.</p></article><article><h3>Central idea</h3><p>A shared edge. Repeated in the mark, the active boundary, paired compositions, and coordinated motion.</p></article></div></section>
<section class="brand-section"><p class="eyebrow">Review materials</p><div class="asset-links">${[['export.html','Export PNG assets'],['research/summary.md','Reference summary'],['research/category.md','Category research'],['research/naming.md','Naming research'],['BRAND-GUIDE.md','Brand guide'],['OUTLINE.md','Page outline'],['COPY.md','Final website copy'],['VALIDATION.md','Validation report'],['README.md','Editing & deployment']].map(([url,label])=>link(url,label+' ↗')).join('')}</div></section></main><footer class="site-footer wrap"><a class="wordmark" href="./">${logo()}</a><p>Brand proposal · Native app integration is separate.</p></footer></body></html>`;

await buildIdentity();
await writeFile('index.html',home);
await writeFile('brand.html',brandPage);
const copyText=home.slice(home.indexOf('<main id="main">'),home.indexOf('</main>'))
  .replace(/<svg[\s\S]*?<\/svg>/g,'')
  .replace(/<h([123])[^>]*>/g,(_,level)=>'\n\n'+'#'.repeat(Number(level)+1)+' ')
  .replace(/<\/h[123]>/g,'\n\n')
  .replace(/<br\s*\/?>/g,' ')
  .replace(/<a[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/g,(_,url,label)=>`[${label.replace(/<[^>]+>/g,'')}](${url})`)
  .replace(/<\/(?:p|li|summary|tr|section|div|figcaption|button)>/g,'\n')
  .replace(/<[^>]+>/g,'')
  .replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&lt;','<')
  .replace(/\n[ \t]+/g,'\n').replace(/\n{3,}/g,'\n\n').trim();
await writeFile('COPY.md',`# ${b.name} — full rendered website copy\n\nGenerated from the working page. Includes section copy and product video captions. Product facts checked ${b.checked}.\n\n${copyText}\n`);
console.log('Rendered website, brand preview, and editable identity assets.');
